version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_HOST=${POSTGRES_HOST:-database}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks:
      - mynet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@gmail.com}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - mynet

  api:
    build: .
    container_name: api
    restart: on-failure
    ports:
      - "8000:8000"   
    environment:
      - USE_POSTGRES_DB=true
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_HOST=${POSTGRES_HOST:-database}
    networks:
      - mynet
  
volumes:
  db-data:
  pgadmin-data: 

networks:
  mynet:
    driver: bridge